name = "socket-state-demo"

workers_dev = true
main = "./build/index.js"
# https://developers.cloudflare.com/workers/platform/compatibility-dates
compatibility_date = "2022-04-05"
compatibility_flags = ["streams_enable_constructors"]

 kv_namespaces = [
  # put here your KV
  { binding = "__example-remix-workers_sites_assets", id = "904e5def2dd240ea88d26a03f190bca7", "preview_id" = "3a056b098d424674a79bc71a4982df02" }
]


[site]
  bucket = "./public"

[build]
  command = "npm run build"

[build.upload]
  format = "modules"

[durable_objects]
bindings = [
  { name = "SOCKET_STATE_DURABLE_OBJECT", class_name = "SocketStateDurableObject" }
]

[[migrations]]
tag = "v2" # Should be unique for each entry
new_classes = ["SocketStateDurableObject"]
